apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: rabbitmq-apps  # Add this line
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  type: ClusterIP
