apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-client-pod
  namespace: rabbitmq-apps
spec:
  containers:
  - name: rabbitmq-client
    image: rabbitmq-client-app:latest
    imagePullPolicy: IfNotPresent  # Add this line
    env:
    - name: RABBITMQ_ADDR
      value: "amqp://guest:guest@rabbitmq-service.rabbitmq-apps.svc.cluster.local:5672/"
